CREATE TABLE IF NOT EXISTS client_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_client_users_email ON client_users (email);

ALTER TABLE appointments
    ADD COLUMN IF NOT EXISTS client_user_id BIGINT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_appointments_client_user'
    ) THEN
        ALTER TABLE appointments
            ADD CONSTRAINT fk_appointments_client_user
                FOREIGN KEY (client_user_id) REFERENCES client_users (id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_appointments_client_user_id ON appointments (client_user_id);
